import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/layout/Navbar";
import Footer from "./components/layout/Footer";

import { Barlow } from 'next/font/google'

const barlow = Barlow({
  weight: ['400', '600'], // Regular + SemiBold
  subsets: ['latin'],
  variable: '--font-barlow'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={barlow.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
